FROM node:latest
ENV LANG C.UTF-8
MAINTAINER Alycat Lee, lucas@alycat.cn
LABEL author=alycat email=lucas@alycat.cn site=https://www.alycat.cn version="1.1"
WORKDIR /
RUN \
  mkdir blog && \
  # install hexo
  npm install hexo-cli -g
WORKDIR /blog
ADD hexo.sh /root/
VOLUME ["/blog"]
ENTRYPOINT ["/bin/bash","/root/hexo.sh"]